configuration:  
  projectName: configclient
server:
  port: 8000
message:
  greeting: Hello Romain!
---
spring:  
  profiles: development
server:  
  port: 8088
message:
  greeting: Hello dev toto!
---
spring:  
  profiles: prod
server:  
  port: 9999
message:
  greeting: Hello prod!
