configuration:  
  projectName: configclient
server:
  port: 9000
message:
  greeting: Hello Romain!
---
spring:  
  profiles: dev
message:
  greeting: Hello dev toto!
galerieslafayette:
  front:
    features:
      guest-checkout:
        enabled: true
        account-create-enable: false
      suggestions:
        enabled: true
      http-https:
        enabled: false
      target-to-sell:
        enabled: true
---
spring:  
  profiles: prod
server:  
  port: 9999
message:
  greeting: Hello prod!
