configuration:  
  projectName: configclient
server:
  port: 9000
message:
  greeting: Hello Romain!
---
spring:  
  profiles: dev,webpack-dev-server
message:
  greeting: Hello dev toto!
---
spring:  
  profiles: prod
server:  
  port: 9999
message:
  greeting: Hello prod!
